### ISSUE TITLE
Return type of gtk.Shortcut*.parseString should be nullable?

### ISSUE THREAD

**Issue by robertgzr** [ianprime0509/zig-gobject#74]
To indicate parsing the provided string failed:

> On success, the parsed action is returned. When parsing failed, NULL is returned.

https://docs.gtk.org/gtk4/ctor.ShortcutTrigger.parse_string.html
https://docs.gtk.org/gtk4/ctor.ShortcutAction.parse_string.html

**Comment by ianprime0509** [comment]
Thank you for pointing this out! It turns out the way I was translating constructors was dropping the return value nullability, and I've fixed it now. The fix will be included in the next released bindings, hopefully soon as I also need to publish bindings for the GNOME 47 SDK.

**Comment by robertgzr** [comment]
thanks!
