### ISSUE TITLE
Can't codegen for Gstreamer. "No GIR file found"

### ISSUE THREAD

**Issue by Nickiel12** [ianprime0509/zig-gobject#81]
Hello! I'm trying to generate gstreamer bindings with this tool, but when I run 
```sh
zig build codegen -Dmodules=Gst-1.0
```
in this cloned repo, I get:
```sh
nixolas@ispypi:~/Documents/zig-gobject $ zig build codegen -Dmodules=Gst-1.0
codegen
└─ install generated/
   └─ run translate-gir (bindings) failure
error: failed to execute xsltproc Gst-1.0: error.FileNotFound
error: failed to find and parse GIR repositories
error: the following command exited with code 1 (expected exited with code 0):
```
Even though the Gst-1.0.gir files are in the /usr/share/gir-1.0 folder:
```sh
nixolas@ispypi:~/Documents/zig-gobject $ ls /usr/share/gir-1.0
CudaGst-1.0.gir       GObject-2.0.gir        GstBadAudio-1.0.gir    GstGLEGL-1.0.gir      GstPlay-1.0.gir        GstVa-1.0.gir             cairo-1.0.gir       xlib-2.0.gir
DBus-1.0.gir          GUdev-1.0.gir          GstBase-1.0.gir        GstGLWayland-1.0.gir  GstPlayer-1.0.gir      GstVideo-1.0.gir          fontconfig-2.0.gir  xrandr-1.3.gir
DBusGLib-1.0.gir      Gio-2.0.gir            GstCheck-1.0.gir       GstGLX11-1.0.gir      GstRtp-1.0.gir         GstVulkan-1.0.gir         freetype2-2.0.gir
GIRepository-2.0.gir  Gst-1.0.gir            GstCodecs-1.0.gir      GstInsertBin-1.0.gir  GstRtsp-1.0.gir        GstVulkanWayland-1.0.gir  gir-1.2.rnc
GL-1.0.gir            GstAllocators-1.0.gir  GstController-1.0.gir  GstMpegts-1.0.gir     GstSdp-1.0.gir         GstVulkanXCB-1.0.gir      libxml2-2.0.gir
GLib-2.0.gir          GstApp-1.0.gir         GstCuda-1.0.gir        GstNet-1.0.gir        GstTag-1.0.gir         GstWebRTC-1.0.gir         xfixes-4.0.gir
GModule-2.0.gir       GstAudio-1.0.gir       GstGL-1.0.gir          GstPbutils-1.0.gir    GstTranscoder-1.0.gir  Vulkan-1.0.gir            xft-2.0.gir
```

**Comment by Nickiel12** [comment]
But it ran fine when I tried to codegen for `GLib-2.0`.

**Comment by Nickiel12** [comment]
Probably separate issue, but I'm going to ask here anyways, When I tried to build with the same tar as nonograms, After updating the code, it's telling me that `gst_init` is `not marked pub`.
```sh
nixolas@ispypi:~/Documents/HailoImageProcessor $ zig build
install
└─ install zig-gst
   └─ zig build-exe zig-gst Debug native 1 errors
src/main.zig:23:8: error: 'gst_init' is not marked 'pub'
    gst.gst_init(@ptrCast(&std.os.argv.len), @ptrCast(&std.os.argv.ptr));
    ~~~^~~~~~~~~
/home/nixolas/.cache/zig/p/12208d70ee791d7ef7e16e1c3c9c1127b57f1ed066a24f87d57fc9f730c5dc394b9d/src/gst1/gst1.zig:18439:8: note: declared here
extern fn gst_init(p_argc: ?*c_int, p_argv: ?[*]*[*:0]u8) void;
~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Is this an overrides thing? If so I would be happy to put in the leg work to get my setup working and upstream the changes.

**Comment by ianprime0509** [comment]
Hi, thanks for your report!

For your first issue, the error message here is not particularly clear, and maybe this (more common) case should be special-cased to give a better message: the issue here is not that `Gst-1.0.gir` is missing, but rather that `xsltproc` is not installed. The external command dependency is a bit unfortunate, but building it using Zig doesn't work very well right now due to https://github.com/ianprime0509/zig-libxml2/issues/1

For your second issue, the generated bindings use "Zig-ified" aliases for functions and other declarations, so in this case the function is named just `gst.init` (and the `extern` declaration `gst_init` is not exposed with that name): https://ianjohnson.dev/zig-gobject/#gst1.init

**Comment by Nickiel12** [comment]
That makes a lot of sense! That fixed both of the things I ran into. Thanks!
